name: Build for all platforms
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Build on all platforms
        run: scripts/build_all_platforms.sh
